create table tb_categoria (id bigint not null auto_increment, nome varchar(255), primary key (id)) engine=InnoDB;
create table tb_endereco (bairro varchar(255), cep varchar(255), complemento varchar(255), localidade varchar(255), logradouro varchar(255), numero varchar(255), pedido_id bigint not null, primary key (pedido_id)) engine=InnoDB;
create table tb_pedido (id bigint not null auto_increment, data_pedido datetime(6), forma_pagamento varchar(255), status varchar(255), cliente_id bigint, primary key (id)) engine=InnoDB;
create table tb_pedido_item (quantidade integer, valor double precision, produto_id bigint not null, pedido_id bigint not null, primary key (pedido_id, produto_id)) engine=InnoDB;
create table tb_permissao (id bigint not null auto_increment, nome varchar(255), primary key (id)) engine=InnoDB;
create table tb_produto (id bigint not null auto_increment, descricao varchar(255), img_url varchar(255), nome varchar(255), preco double precision, categoria_id bigint, primary key (id)) engine=InnoDB;
create table tb_usuario (id bigint not null auto_increment, email varchar(255), nome varchar(255), senha varchar(255), telefone varchar(255), primary key (id)) engine=InnoDB;
create table tb_usuario_permissao (usuario_id bigint not null, permissao_id bigint not null, primary key (usuario_id, permissao_id)) engine=InnoDB;
alter table tb_endereco add constraint FK8rf0gs37sgyqn4d0oi7ld4ybf foreign key (pedido_id) references tb_pedido (id);
alter table tb_pedido add constraint FKj06eek57p4tqwfutx2mvayuyv foreign key (cliente_id) references tb_usuario (id);
alter table tb_pedido_item add constraint FKpowlfcsdrcvdpufsorb53piiw foreign key (produto_id) references tb_produto (id);
alter table tb_pedido_item add constraint FKfxmq0ijavnfj08atxefaech05 foreign key (pedido_id) references tb_pedido (id);
alter table tb_produto add constraint FK1ksfe2oumgjxke3oc5op41lej foreign key (categoria_id) references tb_categoria (id);
alter table tb_usuario_permissao add constraint FKduh5ix0b4v9ns4ehping4wl68 foreign key (permissao_id) references tb_permissao (id);
alter table tb_usuario_permissao add constraint FKse5klwt0ivx37h6opgx6ipjuw foreign key (usuario_id) references tb_usuario (id);
INSERT INTO tb_permissao (nome) VALUES ('ROLE_ADMIN');
INSERT INTO tb_permissao (nome) VALUES ('ROLE_CLIENTE');
INSERT INTO tb_usuario (nome, email, senha, telefone) VALUES ('rafael nunes', 'rafael@gmail.com', '$2a$10$M/9GeDHKrDVZhdGcijy6FOu57mVkmDpFJ2f//4a9P2kY.kdcQ9Eay', '21974315563');
INSERT INTO tb_usuario (nome, email, senha, telefone) VALUES ('Dayane Alves', 'dayane@gmail.com', '$2a$10$M/9GeDHKrDVZhdGcijy6FOu57mVkmDpFJ2f//4a9P2kY.kdcQ9Eay', '21974315563');
INSERT INTO tb_usuario_permissao (usuario_id, permissao_id) VALUES (1, 1);
INSERT INTO tb_usuario_permissao (usuario_id, permissao_id) VALUES (1, 2);
INSERT INTO tb_usuario_permissao (usuario_id, permissao_id) VALUES (2, 2);
INSERT INTO tb_categoria (nome) VALUES ('Hamburguer');
INSERT INTO tb_categoria (nome) VALUES ('Pizza');
INSERT INTO tb_categoria (nome) VALUES ('Hot-Dog');
INSERT INTO tb_categoria (nome) VALUES ('Bebidas');
INSERT INTO tb_categoria (nome) VALUES ('Sobremesas');
INSERT INTO tb_categoria (nome) VALUES ('Açai');
INSERT INTO tb_produto (nome, descricao, img_url, preco, categoria_id) VALUES ('X-Picanha', 'Pão de brioche, queijo cheedar, salada, 150 gr hamburguer de picanha e um molho suculhento', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS1ISm8n6o1S2oSIJA9ILztuMLtp5bikj3uag&usqp=CAU', 18.50, 1);
INSERT INTO tb_produto (nome, descricao, img_url, preco, categoria_id) VALUES ('X-Tudo', 'Pão de brioche, queijo cheedar, salada, 150 gr hamburguer de picanha e um molho suculhento', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSLHEX5O297uUjKuI8byYdkV4OS4HmtxFAHig&usqp=CAU', 12.50, 1);
INSERT INTO tb_produto (nome, descricao, img_url, preco, categoria_id) VALUES ('X-Bacon', 'Pão de brioche, queijo cheedar, salada, 150 gr hamburguer de picanha e um molho suculhento', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSLHEX5O297uUjKuI8byYdkV4OS4HmtxFAHig&usqp=CAU', 15.50, 1);
INSERT INTO tb_produto (nome, descricao, img_url, preco, categoria_id) VALUES ('X-Burguer', 'Pão de brioche, queijo cheedar, salada, 150 gr hamburguer de picanha e um molho suculhento', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSLHEX5O297uUjKuI8byYdkV4OS4HmtxFAHig&usqp=CAU', 9.50, 1);
INSERT INTO tb_produto (nome, descricao, img_url, preco, categoria_id) VALUES ('Pizza Calabresa', 'Pizza média, massa fina, queijo mussarela, molho de tomate. Serve 8 pedaços!', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTr2YTqZuGlpAjKXKA1DZJJ9FB1VT_KHho6zw&usqp=CAU', 19.50, 2);
INSERT INTO tb_produto (nome, descricao, img_url, preco, categoria_id) VALUES ('Pizza Bacon', 'Pizza média, massa fina, queijo mussarela, molho de tomate. Serve 8 pedaços!', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTr2YTqZuGlpAjKXKA1DZJJ9FB1VT_KHho6zw&usqp=CAU', 17.50, 2);
INSERT INTO tb_produto (nome, descricao, img_url, preco, categoria_id) VALUES ('Pizza Portuguesa', 'Pizza média, massa fina, queijo mussarela, molho de tomate. Serve 8 pedaços!', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTr2YTqZuGlpAjKXKA1DZJJ9FB1VT_KHho6zw&usqp=CAU', 22.50, 2);
INSERT INTO tb_produto (nome, descricao, img_url, preco, categoria_id) VALUES ('Coca cola', '2 litros, super gelada!!', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRSCC0rJbDIFnQmUKv915PLSxsW-Kn1S3uVOA&usqp=CAU', 10.00, 4);
INSERT INTO tb_produto (nome, descricao, img_url, preco, categoria_id) VALUES ('Coca cola', '2 litros, super gelada!!', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRSCC0rJbDIFnQmUKv915PLSxsW-Kn1S3uVOA&usqp=CAU', 10.00, 4);
INSERT INTO tb_pedido (data_pedido, forma_pagamento, status, cliente_id) VALUES (TIMESTAMP WITH TIME ZONE '2022-11-01T03:00:00Z', 'DINHEIRO', 'PENDENTE', 1);
INSERT INTO tb_pedido_item (quantidade, valor, produto_id, pedido_id) VALUES (3, 18.5, 1, 1);
INSERT INTO tb_pedido_item (quantidade, valor, produto_id, pedido_id) VALUES (4, 15.5, 3, 1);
INSERT INTO tb_endereco (cep, localidade, bairro, logradouro, numero, complemento, pedido_id) VALUES ('26185010', 'Belford Roxo', 'Jardim Brasil', 'Alameda Argentina', 's/n', 'Lote 06 quadra 08', 1);
INSERT INTO tb_pedido (data_pedido, forma_pagamento, status, cliente_id) VALUES (TIMESTAMP WITH TIME ZONE '2022-11-05T03:00:00Z', 'CARTÃO', 'PREPARANDO', 1);
INSERT INTO tb_pedido_item (quantidade, valor, produto_id, pedido_id) VALUES (1, 17.5, 6, 2);
INSERT INTO tb_pedido_item (quantidade, valor, produto_id, pedido_id) VALUES (1, 10.0, 9, 2);
INSERT INTO tb_endereco (cep, localidade, bairro, logradouro, numero, complemento, pedido_id) VALUES ('26185010', 'Belford Roxo', 'Jardim Brasil', 'Alameda Argentina', 's/n', 'Lote 06 quadra 08', 2);
INSERT INTO tb_pedido (data_pedido, forma_pagamento, status, cliente_id) VALUES (TIMESTAMP WITH TIME ZONE '2022-11-05T03:00:00Z', 'CARTÃO', 'ENVIADO', 1);
INSERT INTO tb_pedido_item (quantidade, valor, produto_id, pedido_id) VALUES (1, 17.5, 6, 3);
INSERT INTO tb_pedido_item (quantidade, valor, produto_id, pedido_id) VALUES (1, 10.0, 9, 3);
INSERT INTO tb_endereco (cep, localidade, bairro, logradouro, numero, complemento, pedido_id) VALUES ('26185010', 'Belford Roxo', 'Jardim Brasil', 'Alameda Argentina', 's/n', 'Lote 06 quadra 08', 3);
INSERT INTO tb_pedido (data_pedido, forma_pagamento, status, cliente_id) VALUES (TIMESTAMP WITH TIME ZONE '2022-11-05T03:00:00Z', 'CARTÃO', 'ENTREGUE', 1);
INSERT INTO tb_pedido_item (quantidade, valor, produto_id, pedido_id) VALUES (1, 17.5, 6, 4);
INSERT INTO tb_pedido_item (quantidade, valor, produto_id, pedido_id) VALUES (1, 10.0, 9, 4);
INSERT INTO tb_endereco (cep, localidade, bairro, logradouro, numero, complemento, pedido_id) VALUES ('26185010', 'Belford Roxo', 'Jardim Brasil', 'Alameda Argentina', 's/n', 'Lote 06 quadra 08', 4);
INSERT INTO tb_pedido (data_pedido, forma_pagamento, status, cliente_id) VALUES (TIMESTAMP WITH TIME ZONE '2022-11-09T03:00:00Z', 'PIX', 'PENDENTE', 2);
INSERT INTO tb_pedido_item (quantidade, valor, produto_id, pedido_id) VALUES (2, 15.5, 3, 5);
INSERT INTO tb_pedido_item (quantidade, valor, produto_id, pedido_id) VALUES (1, 10.0, 9, 5);
INSERT INTO tb_endereco (cep, localidade, bairro, logradouro, numero, complemento, pedido_id) VALUES ('26185010', 'Belford Roxo', 'Jardim Brasil', 'Alameda Argentina', 's/n', 'Lote 06 quadra 08', 5);
INSERT INTO tb_pedido (data_pedido, forma_pagamento, status, cliente_id) VALUES (TIMESTAMP WITH TIME ZONE '2022-11-09T03:00:00Z', 'PIX', 'CANCELADO', 1);
INSERT INTO tb_pedido_item (quantidade, valor, produto_id, pedido_id) VALUES (2, 15.5, 3, 6);
INSERT INTO tb_pedido_item (quantidade, valor, produto_id, pedido_id) VALUES (1, 10.0, 9, 6);
INSERT INTO tb_endereco (cep, localidade, bairro, logradouro, numero, complemento, pedido_id) VALUES ('26185010', 'Belford Roxo', 'Jardim Brasil', 'Alameda Argentina', 's/n', 'Lote 06 quadra 08', 6);
